### ISSUE TITLE
Make generator available on npm

### ISSUE THREAD

**Issue by vilongpr** [abusque/qng#4]
It would be super useful to be able to use this package from npm in web project.

**Comment by vilongpr** [comment]
Ça srais trop queb de générer des noms Queb en javascript pis toute.

**Comment by abusque** [comment]
That could be nice but I think it might be out of scope for this project since I'd have write a second JavaScript version. Feel free to re-use the data I scraped and the scraping scripts if you'd like to write your own though.

**Comment by vilongpr** [comment]
Will do, thanks!!
